[package]
name = "guessing_game"
version = "0.1.0"
authors = ["Joseph Timothy Foley <foley@ru.is>"]
edition = "2018"
license = "MIT OR Apache-2.0"
description = "A fun game where you guess what number the computer has chosen."

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rand = "0.5.5"